// https://linguistics.ucla.edu/people/hayes/120a/Index.htm#features
const hayes = {
    "ɒ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "+",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɑ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "+",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɶ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "+",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "a": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "+",
        "front": "-",
        "back": "-",
        "tense": "0"
    },
    "æ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "+",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ʌ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "-"
    },
    "ɔ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "-"
    },
    "o": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "+"
    },
    "ɤ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "+"
    },
    "ɘ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "+"
    },
    "œ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "-"
    },
    "ə": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "-"
    },
    "e": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "+"
    },
    "ɞ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "-"
    },
    "ø": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "+"
    },
    "ɛ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "-"
    },
    "ɵ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "+"
    },
    "ɯ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "+"
    },
    "u": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "+"
    },
    "ʊ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "-"
    },
    "ɨ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "+"
    },
    "ʉ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "+"
    },
    "y": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "+"
    },
    "i": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "+"
    },
    "ʏ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "-"
    },
    "ɪ": {
        "syllabic": "+",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "-"
    },
    "ŋ+": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ʟ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "+",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɫ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɴ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ʀ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "+",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɲ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ʎ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ŋ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ŋ˗": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ʟ̠": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "+",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɳ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ʙ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "+",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɭ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɺ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "+",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɻ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɽ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "+",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "r": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "+",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "n": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "m": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "l": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɾ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "+",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɱ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "+",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ʔ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "+",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɣ+": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "x+": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "k+": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ɡ+": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "k+͡x+": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ɡ+͡ɣ+": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ħ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "+",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ʕ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "+",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ʁ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "q": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "χ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɢ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɕ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ɉ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ʝ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "c": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ç": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "d͡ʑ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "t͡ɕ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ɣ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɣ̠ ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "x": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "x̠": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "k": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "k̠": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɡ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɡ̠": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ʑ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ʈ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɖ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɬ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ʐ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɸ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ʂ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ʒ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "z": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "v": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "+",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "t": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ʃ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "s": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "p": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "f": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "+",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "d": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "b": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "θ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɮ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ð": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "β": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "d͡ʒ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "d͡z": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "d͡ɮ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "d̠͡ɮ̠": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "t͡ʃ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "t̠͡ɬ̠": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "t͡s": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "t͡ɬ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "t̪͡s̪": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "t̪͡ɬ̪": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "d̪͡z̪": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "d̪͡ɮ̪": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "-",
        "lateral": "+",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ʈ͡ʂ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɖ͡ʐ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "p͡f": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "+",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "b͡v": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "+",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "p͡ɸ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "b͡β": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "t̪͡θ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "d̪͡ð": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "c͡ç": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "ɉ͡ʝ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "0"
    },
    "k͡x": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "k̠͡x̠": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɡ͡ɣ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɡ̠̠͡ɣ̠": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "q͡χ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɢ͡ʁ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "0"
    },
    "ɧ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "k͡p": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "g͡b": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "p͡t": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "b͡d": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "+",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "+",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ɰ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "0",
        "back": "0",
        "tense": "+"
    },
    "ɰ̠": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "+"
    },
    "w": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "+"
    },
    "ɥ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "+"
    },
    "j": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "+"
    },
    "ɹ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ʋ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "approximant": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "-",
        "labiodental": "+",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "ʍ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "+",
        "constr gl": "-",
        "LABIAL": "+",
        "round": "+",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "+"
    },
    "ɦ": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "+",
        "spread gl": "+",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    },
    "h": {
        "syllabic": "-",
        "stress": "-",
        "long": "-",
        "consonantal": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "approximant": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "voice": "-",
        "spread gl": "+",
        "constr gl": "-",
        "LABIAL": "-",
        "round": "-",
        "labiodental": "-",
        "CORONAL": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "lateral": "-",
        "DORSAL": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0"
    }
};